SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";
CREATE TABLE `tasks` (
  `ID` int(11) NOT NULL,
  `NAME` char(32) CHARACTER SET utf8 COLLATE utf8_polish_ci NOT NULL,
  `DESCRIPTION` char(64) CHARACTER SET utf8 COLLATE utf8_polish_ci NOT NULL,
  `DATE` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;
ALTER TABLE `tasks`
  ADD PRIMARY KEY (`ID`);
ALTER TABLE `tasks`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT;
COMMIT;